### ISSUE TITLE
"Not enough mana" regardless of current mana pool

### ISSUE THREAD

**Issue by hellbringer616** [NeumimTo/NT-RPG#43] opened 2018-03-21 23:12 UTC
Dev build: 71da216
Sponge API 7.1
-----------------------
**[ISSUE:]**
When using Bandage, Multibolt, or BurningPresence i receive the message "Not enough mana"
this issue happens regardless of manacost set in the skill.conf files

Other skills are as of yet untested.

When setting manacost in Arrowstorm the skill functions perfectly, mana is deducted and the skill is cast.

**Example SkillSettings for Bandage:**
>    SkillSettings: {
> 		healed_amount: 5,
> 		range: 3,
> 		range_levelbonus: 0,
> 		healed_amount_levelbonus: 1,
> 		manacost: 2,
> 		manacost_levelbonus: 2,
> 		cooldown: 30000,
> 		cooldown_levelbonus: -500
	}

**Example of SkillSettings for Arrowstorm:**
>    SkillSettings: {
> 		damage: 6,
> 		period: 100,
> 		min-arrows_levelbonus: 1,
> 		period_levelbonus: -10,
> 		min-arrows: 4,
> 		max-arrows: 16,
> 		damage_levelbonus: 2,
> 		max-arrow_levelbonus: 2,
> 		manacost: 2,
> 		manacost_levelbonus: 2,
> 		cooldown: 60000,
> 		cooldown_levelbonus: -10000
> 	}

[Link to skill.confs](https://github.com/hellbringer616/NT-RPG-Configs-And-Assets/tree/master/skilltrees)

**Comment by NeumimTo** [comment] 2018-03-22 07:54
Thats strange since mana checks are done in part of code which is shared for all skills. there should not be any differences. 

The rest of your configs is from here? https://github.com/NeumimTo/NT-RPG-Configs-And-Assets/pull/1 
I need to reproduce it somehow

**Comment by hellbringer616** [comment] 2018-03-22 11:56
Yes, that pull request is where i post my lastest files.
Races, Classes, and their respective skilltrees are there, latest pull has everything.

Direct link to the source Git: https://github.com/hellbringer616/NT-RPG-Configs-And-Assets

**Comment by NeumimTo** [comment] 2018-03-22 22:54
Fixed in a chanes ending with commit d9024ff

**Closed by NeumimTo** 2018-03-22 22:54 UTC
